shellcheck

diff --git a/doasedit b/doasedit
--- a/doasedit
+++ b/doasedit
@@ -47,10 +47,10 @@ error() {
 alphanum() {
     if [ -c "${RANDOM_DEVICE}" ]; then
         # Use od utility if /dev/random or /dev/urandom exists, od is used in most of systems
-        printf "%s" $(od -vN4 -An -tx1 ${RANDOM_DEVICE} | tr -d " \n") || error "cannot generate alphanumeric string"
+        printf "%s" "$(od -vN4 -An -tx1 ${RANDOM_DEVICE} | tr -d ' \n')" || error "cannot generate alphanumeric string"
     else
         # Most POSIX way I found to generate alphanumeric string via awk (POSIX)
-        printf "%s" $(awk 'BEGIN { srand(); s=""; chars="abcdefghijklmnopqrstuvwxyz0123456789"; for(i=0;i<8;i++) { s=s""substr(chars,int(rand()*36),1); } print s }') || error "cannot generate alphanumeric string"
+        printf "%s" "$(awk 'BEGIN { srand(); s=""; chars="abcdefghijklmnopqrstuvwxyz0123456789"; for(i=0;i<8;i++) { s=s""substr(chars,int(rand()*36),1); } print s }')" || error "cannot generate alphanumeric string"
 
     fi
 }
@@ -92,9 +92,10 @@ readlinkf() {
     return 1
 }
 
+# Create temporary directory
 mktempd() {
     dir="${TMPDIR}/$(alphanum).tmp" && mkdir "${dir}"
-    [ -d ${dir} ] && printf "${dir}" || error "cannot create temporary directory"
+    [ -d "${dir}" ] && printf "${dir}" || error "cannot create temporary directory"
 }
 
 # Reset doas password promt. If you want, feel free to comment this
