I still have not commit it: use readlinkf_posix to do it even more POSIX-compliant

diff --git a/doasedit b/doasedit
--- a/doasedit
+++ b/doasedit
@@ -20,12 +20,12 @@ export RANDOM_DEVICE=/dev/urandom
 
 # Throw information message
 msg() {
-    printf "%s\n" "$(basename ${0}): ${1}"
+    printf "%s\n" "doasedit: ${1}"
 }
 
 # Throw error message
 error() {
-    printf "%s\n" "$(basename ${0}): ${1}" 2>&1
+    printf "%s\n" "doasedit: ${1}" >&2
     exit 1
 }
 
@@ -58,51 +58,15 @@ randstr() {
     fi
 }
 
-# POSIX compliant version of readlink
-# Credit: https://github.com/ko1nksm/readlinkf
-readlinkf() {
-    [ "${1:-}" ] || return 1
-    max_symlinks=40
-    # to avoid changing to an unexpected directory
-    CDPATH=''
-    target=$1
-    # trim trailing slashes
-    [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"}
-    [ -d "${target:-/}" ] && target="$target/"
-    cd -P . 2>/dev/null || return 1
-    while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
-        if [ ! "$target" = "${target%/*}" ]; then
-            case $target in
-                /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
-                *) cd -P "./${target%/*}" 2>/dev/null || break ;;
-            esac
-            target=${target##*/}
-        fi
-        if [ ! -L "$target" ]; then
-            target="${PWD%/}${target:+/}${target}"
-            printf '%s\n' "${target:-/}"
-            return 0
-        fi
-        # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ls.html
-        link=$(ls -dl -- "$target" 2>/dev/null) || break
-        target=${link#*" $target -> "}
-    done
-    return 1
-}
-
 # Create temporary directory
 mktempd() {
     dir="${TMPDIR}/$(randstr).tmp" && mkdir "${dir}"
     [ -d "${dir}" ] && printf "${dir}" || error "cannot create temporary directory"
 }
 
-# Reset doas password promt. If you want, feel free to comment this
-case "$(uname -s | tr '[:upper:]' '[:lower:]')" in
-    linux) doas -L ;;
-esac
-
 # Absolute path to the source file (file for editing)
-src="$(readlinkf "${1}")"
+# readlinkf_posix utility should be provided from the same repository as doasedit
+src="$(doas readlinkf_posix "${1}")"
 
 # Filename for the source file
 filename="${src##*/}"
@@ -136,16 +100,11 @@ if [ -w "$src" ]; then
     error "$filename: editing files in a writable directory is not permitted"
 fi
 
-# Other conditions: if file exist, readable, et cetera
-if [ -f "${src}" ] && [ ! -r "${src}" ]; then
-    doas cat "${src}" > "${tmp_f}" || error "the file is not readable"
+# Other conditions
+if [ ! -r "${src}" ] && doas [ -f ${src} ]; then
+    doas cat "${src}" > "${tmp_f}" 2>/dev/null || error "cannot transfer the content of the file to temporary one"
 elif [ -r "${src}" ]; then
-    cat "${src}" > "${tmp_f}" || error "cannot transfer to content of the file to temporary one"
-elif [ ! -f "${src}" ]; then
-    # Grant .rw-r--r-- permission for newly created files by default owned by root
-    :> "${tmp_f}" && doas chmod -R 0644 "${tmp_f}" || error "cannot create new file"
-else
-    error "unexpected script behaviour"
+    cat "${src}" > "${tmp_f}" 2>/dev/null || error "cannot transfer the content of the file to temporary one"
 fi
 
 # Create copy of the temporary file
